#!/usr/bin/env bash
# shellcheck disable=SC2086
# Script that displays the record type among other info of a domain.
display_info () {
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}
for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ]; then
	display_info "$1" "$subdomain"
    fi
done
