#!/usr/bin/env bash
# Script that configures a new Ubuntu machine and configure the Nginx server to redirect to another page.
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sed -i "19i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
service nginx restart
