#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to distribute requests using a roundrobin algorithm.
apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy=1.8.\*
echo "frontend http
        bind *:80
        mode http
        default_backend web-backend
    backend web-backend
        balance roundrobin
        server 1610-web-01 104.196.209.226:80 check
        server 1610-web-02 34.75.152.150:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
