#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a compressed archive out of it.
name=$(date +"%d-%m-%Y")
mysqldump -u root --password="$1" --all-databases > backup.sql
tar -czvf "$name".tar.gz backup.sql
