#!/usr/bin/env bash
# Script that displays numbers from 1 to 100 and displays different
# strings acording to the multiple of the number.

n=1
while [ "$n" -le 100 ]
do
    if [ $((n%15)) == 0 ]
    then
        echo "FizzBuzz"
    elif [ $((n%3)) == 0 ]
    then
        echo "Fizz"
    elif [ $((n%5)) == 0 ]
    then
        echo "Buzz"
    else
        echo "$n"
    fi
    n=$((n + 1))
done
