#!/usr/bin/env bash
# Script that displays the visitor IP along with the HTTP status code from the
# Apache log file, Ordered from the greatest to the lowest number of occurrences.

awk -F" " ' { print $1, $9} ' apache-access.log | sort | uniq -c | sort -nr