#!/usr/bin/env bash
# Script that loops from 1 to 10 and displays different srtrings according to
# the nth iteration.

i=0
while [ $i -lt 10 ]
do
    if [ $i = 3 ]
    then
        echo "bad luck"
    elif [ $i = 7 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    i=$((i + 1))
done
