#!/usr/bin/env bash
# Script that loops from 1 to 20 and displays different srtrings according to
# the nth iteration.

i=1
while [ $i -lt 21 ]
do
    echo "$i"
    case $i in
        4 )
            echo "bad luck from China" ;;
        9 )
            echo "bad luck from Japan" ;;
        17 )
            echo "bad luck from Italy" ;;
    esac
    i=$((i + 1))
done
