#!/usr/bin/env bash
# Script that displays: The content of the current directory In a list format
# Where only the part of the name after the first dash is displayed.

for filename in *
do
    echo "$filename" | cut -d "-" -f2
done
