#!/usr/bin/env bash
# Script that changes the user of Nginx so this stop running on root.
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 0700 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
